jobs:
    include:
        - stage: test
          script: npm test
          language: node_js
          node_js:
              - '10'
        - stage: build docker image
          services:
              - docker
          script:
              - export REPO=securecodebox/sslyze
              - export TAG=$(echo $TRAVIS_BRANCH | sed 's/\//-/g')
              - echo -en "travis_fold:start:Docker_Build\r"
              - docker build -t $REPO:$TAG --build-arg="BUILD_DATE=$(date --rfc-3339=seconds)" --build-arg=VERSION=$TRAVIS_TAG --build-arg=COMMIT_ID=$TRAVIS_COMMIT --build-arg=BRANCH=$TRAVIS_BRANCH --build-arg=REPOSITORY_URL="https://github.com/secureCodeBox/scanner-infrastructure-sslyze" .
              - echo -en "travis_fold:end:Docker_Build\r"
deploy:
    - provider: script
      skip_cleanup: true
      script: bash .travis/deployDockerHub.sh
      on:
          all_branches: true
